---
version: 2

registries:

  coop-ghcr:
    type: docker-registry
    url: ghcr.io
    username: CoopGithubServiceaccount
    password: ${{ secrets.DEPENDABOT_GHCR_PULL }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    registries:
      - coop-ghcr
    ignore:
      - dependency-name: "hashicorp/terraform"
        versions: ">= 1.6.0"
  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
