# Do not remove, used by pallet validation
FROM ghcr.io/coopnorge/engineering-docker-images/e0/devtools-kubernetes-v1beta1:latest@sha256:ce2c60e53291afe1cc6cdb8fa312d008cc2dcf05470e188f67077f733a2a73a6 AS kubernetes-devtools
FROM ghcr.io/coopnorge/engineering-docker-images/e0/techdocs:latest@sha256:0308210c2e26872edbac749455000ef5c05c704584d0fd850f3b0e6d4be1294b AS techdocs
