# Do not remove, used by pallet validation
FROM ghcr.io/coopnorge/engineering-docker-images/e0/devtools-kubernetes-v1beta1:latest@sha256:8c10c3204baf469c51ada1b90438319df93f067269c0de9777e86799b537c983 AS kubernetes-devtools
