package core

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strings"

	doublestar "github.com/bmatcuk/doublestar/v4"
	"github.com/magefile/mage/sh"
)

const (
	// OutputDir is the destination for CI artifacts
	OutputDir = "./var"
)

// GetRelativeRootPath ...
func GetRelativeRootPath(absRootPath, workDirRel string) (string, error) {
	workDirAbs := path.Join(absRootPath, workDirRel)
	relativeRootPath, err := filepath.Rel(workDirAbs, absRootPath)
	if err != nil {
		return "", err
	}
	return relativeRootPath, nil
}

// WriteTempFile writes the content to a temp file in the provided with a
// random prefix and the provided suffix. Returns a cleanup function that the
// caller is expected to call. If cleanup errors it will panic.
func WriteTempFile(directory, suffix, content string) (string, func(), error) {
	err := os.MkdirAll(directory, 0o700)
	if err != nil {
		return "", func() {}, err
	}
	file, err := os.CreateTemp(directory, fmt.Sprintf("*-%s", suffix))
	if err != nil {
		return "", func() {}, err
	}

	cleanup := func() {
		// check if file exist if not skip deletion
		_, err := os.Stat(file.Name())
		if errors.Is(err, os.ErrNotExist) {
			return
		}
		if err != nil {
			panic(err)
		}
		err = os.Remove(file.Name())
		if err != nil {
			panic(err)
		}
	}

	_, err = file.WriteString(content)
	if err != nil {
		defer cleanup()
		return "", func() {}, err
	}
	return file.Name(), cleanup, nil
}

// MkdirTemp creates a new temporary directory in the default directory for
// temporary files, as returned by TempDir, and returns the pathname of the new
// directory. The new directory's name is generated by adding a random string
// to the end of the name of the directory of the repository. The directory is
// created with mode 0o700 (before umask). Multiple programs or goroutines
// calling MkdirTemp simultaneously will not choose the same directory. It is
// the caller's responsibility to call the returned cleanup function when the
// directory is no longer needed. If cleanup errors it will panic.
func MkdirTemp() (string, func(), error) {
	workDir, err := os.Getwd()
	if err != nil {
		return "", func() {}, err
	}
	path, err := os.MkdirTemp("", path.Base(workDir))
	if err != nil {
		return "", func() {}, err
	}
	cleanup := func() {
		err := os.RemoveAll(path)
		// Dont panic in CI. GHA  has some issues with deleting
		if err != nil && os.Getenv("CI") != "true" {
			panic(err)
		}
	}
	return path, cleanup, nil
}

// IsDotDirectory checks if the supplied direcory is starts with a dot.
func IsDotDirectory(path string, d fs.DirEntry) bool {
	if !d.IsDir() {
		return false
	}
	if filepath.Base(path) == "." {
		return false
	}
	return strings.HasPrefix(filepath.Base(path), ".")
}

// CompareChangesToPaths takes a list of paths comapring if the first matches
// the latter. You can also add additional globs to match the first list.
func CompareChangesToPaths(changes []string, paths []string, additionalGlobs []string) (bool, error) {
	for _, change := range changes {
		for _, p := range paths {
			if change == p {
				return true, nil
			}

			match, err := path.Match(fmt.Sprintf("%s/*", p), change)
			if err != nil {
				return false, err
			}
			if match {
				return true, nil
			}
		}
		for _, pattern := range additionalGlobs {
			if pattern == "" {
				continue
			}
			matchAdditional, err := doublestar.Match(pattern, change)
			if err != nil {
				return false, err
			}
			if matchAdditional {
				return true, nil
			}
		}
	}
	return false, nil
}

// Verbose returns true if the magefile is running in verbose mode.
func Verbose() bool {
	// Check for the MAGEFILE_VERBOSE environment variable
	v := os.Getenv("MAGEFILE_VERBOSE")
	return v == "1" || strings.EqualFold(v, "true")
}

// FileExists checks if a file exists at the given path.
// Returns true if the file exists, false otherwise.
func FileExists(filePath string) bool {
	_, err := os.Stat(filePath)
	return err == nil
}

// FileExistsInDirectory checks if a file with the given name exists in the specified directory.
// Returns true if the file exists, false otherwise.
func FileExistsInDirectory(directory, filename string) bool {
	fullPath := filepath.Join(directory, filename)
	return FileExists(fullPath)
}

// GetRepoRoot returns the absolute path to the repository root directory.
// It uses git to find the top-level directory of the repository.
// If git is not available or not in a git repository, it falls back to the current working directory.
func GetRepoRoot() (string, error) {
	// Try to get repo root from git
	repoRoot, err := sh.Output("git", "rev-parse", "--show-toplevel")
	if err == nil {
		return strings.TrimSpace(repoRoot), nil
	}

	// Fallback to current working directory if not in a git repo
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return cwd, nil
}

// ListRescursiveFiles recursively finds all files in the root directory that match the given pattern.
func ListRescursiveFiles(root, pattern string) ([]string, error) {
	var matches []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			// If an error occurs (e.g., permission denied on a directory),
			// the function can decide how to handle it. Returning nil skips the error
			// for this specific path and continues the traversal.
			return nil
		}

		// Check if it's a file and if its name matches the pattern.
		if !d.IsDir() {
			// filepath.Match checks a filename against a glob pattern.
			if matched, _ := filepath.Match(pattern, d.Name()); matched {
				// make relateive
				relPath, err := filepath.Rel(root, path)
				if err != nil {
					return err
				}
				matches = append(matches, relPath)
			}
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("error walking directory: %w", err)
	}

	return matches, nil
}

// DirExists returns true if a dir exists
func DirExists(path string) bool {
	_, err := os.Stat(path)
	if err == nil {
		return true
	}
	if errors.Is(err, fs.ErrNotExist) {
		return false
	}
	return false
}

// GetAbsWorkDir accepts a directory as string and joins it with the current workdir
// directory to return a absolute directory. If the supplied directory is
// already absolute it will just return the input.
func GetAbsWorkDir(workdir string) string {
	if filepath.IsAbs(workdir) {
		return workdir
	}
	cwd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	return filepath.Join(cwd, workdir)
}

// CopyFiles copies a file from src to dst.
func CopyFile(src, dst string) error {
	source, err := os.Open(src)
	if err != nil {
		return err
	}
	defer source.Close() // Reading close is usually safe to defer

	destination, err := os.Create(dst)
	if err != nil {
		return err
	}

	// io.Copy does the heavy lifting
	if _, err := io.Copy(destination, source); err != nil {
		destination.Close() // Close but prioritize returning the Copy error
		return err
	}

	// Manually close to catch write/flush errors
	return destination.Close()
}
