concurrency:
  group: reusable-pallets-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    inputs: {}
    secrets: {}

jobs:
  validate-pallet-config:
    name: Pallets config check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup coop-mage
        uses: coopnorge/github-action-setup-mage@v0.0.3

      - name: Pallet config validation
        id: validate
        run: coop-mage pallets:validate
