concurrency:
  group: reusable-goapp-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    secrets: {}
    inputs:
      oci-image-base:
        type: string
        required: true
      push-oci-image:
        type: boolean
        required: false
        default: false
      workload-identity-provider:
        type: string
        required: true
      service-account:
        type: string
      artifact-registry-location:
        type: string
        default: "europe"
        description: Artifact registry region name (e.g. "europe", "europe-north1").
      go-runtime:
        type: string
        default: "docker"
        description: Run mage go related tasks in "docker" (default) or local
      tag-based-diff:
        type: boolean
        default: true
        required: false
        description: If true it will create a github release based on the tag of the OCI
      skip-lint-and-test-on-main:
        type: boolean
        default: false
        required: false
        description: If set to true, skip the Lint and Test jobs on the main branch. Will still run on pull requests and other branches.
    outputs:
      oci-images:
        value: ${{ jobs.go-build-and-push.outputs.oci-images || '{}' }}
        description: OCI image references.

jobs:
  go-lint:
    name: Go Lint
    if: ${{ github.ref != 'refs/heads/main' || inputs.skip-lint-and-test-on-main == false }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Configure access to internal and private GitHub repos
        run: git config --global url."https://${{ secrets.REVIEWBOT_GITHUB_TOKEN }}:x-oauth-basic@github.com/coopnorge".insteadOf "https://github.com/coopnorge"
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
          cache-dependency-path: "**/go.sum"
      - name: Setup Golangci Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          install-only: true
      - name: Check if coop mage has separeate build commands
        id: has-multiple-cmds
        run: echo "outcome=$(go tool mage -l | grep go:buildBinaries | wc -l)" >> $GITHUB_OUTPUT
      - name: Download Go modules
        if: ${{ steps.has-multiple-cmds.outputs.outcome == '1' }}
        run: "go tool mage -v go:downloadModules"
      - name: Run Go Lint
        if: ${{ steps.has-multiple-cmds.outputs.outcome == '1' }}
        run: "go tool mage -v go:lint"
        env:
          GO_RUNTIME: ${{ inputs.go-runtime }}

  go-test:
    name: Go Test
    if: ${{ github.ref != 'refs/heads/main' || inputs.skip-lint-and-test-on-main == false }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Configure access to internal and private GitHub repos
        run: git config --global url."https://${{ secrets.REVIEWBOT_GITHUB_TOKEN }}:x-oauth-basic@github.com/coopnorge".insteadOf "https://github.com/coopnorge"
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
          cache-dependency-path: "**/go.sum"
      - name: Check if coop mage has separate build commands
        id: has-multiple-cmds
        run: echo "outcome=$(go tool mage -l | grep go:buildBinaries | wc -l)" >> $GITHUB_OUTPUT
      - name: Download Go modules
        if: ${{ steps.has-multiple-cmds.outputs.outcome == '1' }}
        run: "go tool mage -v go:downloadModules"
      - name: Run Go Test
        if: ${{ steps.has-multiple-cmds.outputs.outcome == '1' }}
        run: "go tool mage -v go:test"
        env:
          GO_RUNTIME: ${{ inputs.go-runtime }}

  go-build:
    name: Go build
    if: ${{ github.ref != 'refs/heads/main' }}
    uses: ./.github/workflows/reusable-goapp-build.yaml
    permissions:
      contents: read
      packages: read
    secrets: inherit
    with:
      oci-image-base: ${{ inputs.oci-image-base }}
      push: false
      go-runtime: ${{ inputs.go-runtime }}

  go-build-and-push:
    name: Go build and push
    needs:
      - go-lint
      - go-test
    if: ${{ always() && github.ref == 'refs/heads/main' && (inputs.skip-lint-and-test-on-main || (needs.go-lint.result == 'success' && needs.go-test.result == 'success')) }}
    uses: ./.github/workflows/reusable-goapp-build.yaml
    permissions:
      contents: write
      id-token: write
      packages: read
    secrets: inherit
    with:
      oci-image-base: ${{ inputs.oci-image-base }}
      push: true
      push-oci-image: ${{ inputs.push-oci-image }}
      workload-identity-provider: ${{ inputs.workload-identity-provider }}
      service-account: ${{ inputs.service-account }}
      artifact-registry-location: ${{ inputs.artifact-registry-location }}
      go-runtime: ${{ inputs.go-runtime }}
      tag-based-diff: ${{ inputs.tag-based-diff }}
