concurrency:
  group: reusable-pallets-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    inputs: {}
    secrets: {}

jobs:
  validate-pallet-config:
    name: Pallets config check
    runs-on:
      group: larger-runners
      labels: ubuntu-latest-8-cores
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
          cache-dependency-path: "**/go.sum"

      - name: Pallet config validation
        id: validate
        run: go tool mage pallets:validate
