concurrency:
  group: reusable-catalog-info-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    inputs: {}
    secrets: {}

jobs:
  validate-catalog-info:
    name: Catalog info validator
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.27.1" # renovate: datasource=docker depName=docker.io/library/golang
          cache-dependency-path: "**/go.sum"

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: Iv23liFKpdpVm7O1CJiq
          private-key: ${{ secrets.MAGE_CATALOGINFO_APP_PEM }}

      - name: Catalog Info Validation
        id: validate
        # TODO replace with github app. Needs only org read scope
        env:
          GITHUB_TOKEN: ${{ secrets.REVIEWBOT_GITHUB_TOKEN }}
        run: go tool mage catalogInfo:validate
